//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERISTICAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARACTERISTICAS()
        {
            this.RECURSO_TECNOLOGICO_X_CARACTERISTICA = new HashSet<RECURSO_TECNOLOGICO_X_CARACTERISTICA>();
            this.TIPOS_RECURSOS_TECNOLOGICOS = new HashSet<TIPOS_RECURSOS_TECNOLOGICOS>();
        }
    
        public int id_caracteristica { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public string descripcion { get; set; }
    
        public virtual UNIDADES_MEDIDAS UNIDADES_MEDIDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSO_TECNOLOGICO_X_CARACTERISTICA> RECURSO_TECNOLOGICO_X_CARACTERISTICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOS_RECURSOS_TECNOLOGICOS> TIPOS_RECURSOS_TECNOLOGICOS { get; set; }
    }
}
