//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECTORE()
        {
            this.HISTORIAL_DIRECTORES = new HashSet<HISTORIAL_DIRECTORES>();
        }
    
        public int id_director { get; set; }
        public Nullable<int> id_personal_cientifico { get; set; }
    
        public virtual PERSONAL_CIENTIFICO PERSONAL_CIENTIFICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_DIRECTORES> HISTORIAL_DIRECTORES { get; set; }
    }
}
