//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTORES
    {
        public int id_director { get; set; }
        public int id_personal_cientifico { get; set; }
        public int id_centro_investigacion { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha_hora_inicio { get; set; }
        public Nullable<System.DateTime> fecha_hora_fin { get; set; }
    
        public virtual CENTRO_INVESTIGACION CENTRO_INVESTIGACION { get; set; }
        public virtual PERSONAL_CIENTIFICO PERSONAL_CIENTIFICO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
