//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTENSION_MANTENIMIENTO
    {
        public int id_extension_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public Nullable<System.DateTime> fecha_fin_prevista { get; set; }
        public string motivo { get; set; }
        public Nullable<int> id_mantenimiento { get; set; }
    
        public virtual MANTENIMIENTO MANTENIMIENTO { get; set; }
    }
}
