//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMBITOS> AMBITOS { get; set; }
        public virtual DbSet<CARACTERISTICAS> CARACTERISTICAS { get; set; }
        public virtual DbSet<CENTRO_INVESTIGACION> CENTRO_INVESTIGACION { get; set; }
        public virtual DbSet<CIENTIFICOS> CIENTIFICOS { get; set; }
        public virtual DbSet<DIRECTORES> DIRECTORES { get; set; }
        public virtual DbSet<DISPONIBILIDAD> DISPONIBILIDAD { get; set; }
        public virtual DbSet<ESTADOS> ESTADOS { get; set; }
        public virtual DbSet<EXTENSION_MANTENIMIENTO> EXTENSION_MANTENIMIENTO { get; set; }
        public virtual DbSet<FACULTADES> FACULTADES { get; set; }
        public virtual DbSet<HISTORIAL_RECURSO_TECNOLOGICO> HISTORIAL_RECURSO_TECNOLOGICO { get; set; }
        public virtual DbSet<HISTORIALES_ESTADOS> HISTORIALES_ESTADOS { get; set; }
        public virtual DbSet<MANTENIMIENTO> MANTENIMIENTO { get; set; }
        public virtual DbSet<MARCAS> MARCAS { get; set; }
        public virtual DbSet<MODELOS> MODELOS { get; set; }
        public virtual DbSet<PERFILES> PERFILES { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PERSONAL_CIENTIFICO> PERSONAL_CIENTIFICO { get; set; }
        public virtual DbSet<RECURSO_TECNOLOGICO_X_CARACTERISTICA> RECURSO_TECNOLOGICO_X_CARACTERISTICA { get; set; }
        public virtual DbSet<RECURSOS_TECNOLOGICOS> RECURSOS_TECNOLOGICOS { get; set; }
        public virtual DbSet<RESPONSABLES_TECNICOS> RESPONSABLES_TECNICOS { get; set; }
        public virtual DbSet<SESIONES> SESIONES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOS_MANTENIMIENTOS> TIPOS_MANTENIMIENTOS { get; set; }
        public virtual DbSet<TIPOS_RECURSOS_TECNOLOGICOS> TIPOS_RECURSOS_TECNOLOGICOS { get; set; }
        public virtual DbSet<TURNO> TURNO { get; set; }
        public virtual DbSet<UNIDADES_MEDIDAS> UNIDADES_MEDIDAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
