//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_DIRECTORES
    {
        public int id_historial_director { get; set; }
        public int id_director { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
    
        public virtual DIRECTORE DIRECTORE { get; set; }
    }
}
