//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALES_ESTADOS
    {
        public int id_historial_estado { get; set; }
        public int id_turno { get; set; }
        public int id_estado { get; set; }
        public Nullable<System.DateTime> fecha_hora_inicio { get; set; }
        public Nullable<System.DateTime> fecha_hora_fin { get; set; }
    
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual TURNO TURNO { get; set; }
    }
}
