//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANTENIMIENTO()
        {
            this.EXTENSION_MANTENIMIENTO = new HashSet<EXTENSION_MANTENIMIENTO>();
        }
    
        public int id_mantenimiento { get; set; }
        public int id_recurso_tecnologico { get; set; }
        public int id_tipo_mantenimiento { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public Nullable<System.DateTime> fecha_hora_inicio_mantenimiento { get; set; }
        public System.DateTime fecha_hora_fin_mantenimiento_prevista { get; set; }
        public Nullable<System.DateTime> fecha_hora_fin_mantenimiento_real { get; set; }
        public string motivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTENSION_MANTENIMIENTO> EXTENSION_MANTENIMIENTO { get; set; }
        public virtual RECURSOS_TECNOLOGICOS RECURSOS_TECNOLOGICOS { get; set; }
        public virtual TIPOS_MANTENIMIENTOS TIPOS_MANTENIMIENTOS { get; set; }
    }
}
