//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTO
    {
        public int id_mantenimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public int id_tipo_mantenimiento { get; set; }
        public int id_recurso_tecnologico { get; set; }
    
        public virtual RECURSOS_TECNOLOGICOS RECURSOS_TECNOLOGICOS { get; set; }
        public virtual TIPOS_MANTENIMIENTOS TIPOS_MANTENIMIENTOS { get; set; }
    }
}
