//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_CIENTIFICO_X_CENTRO_INVESTIGACION
    {
        public int id_centro_investigacion { get; set; }
        public int id_personal_cientifico { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
    
        public virtual CENTRO_INVESTIGACION CENTRO_INVESTIGACION { get; set; }
        public virtual PERSONAL_CIENTIFICO PERSONAL_CIENTIFICO { get; set; }
    }
}
