//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSOS_TECNOLOGICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECURSOS_TECNOLOGICOS()
        {
            this.DISPONIBILIDADs = new HashSet<DISPONIBILIDAD>();
            this.HISTORIAL_RECURSO_TECNOLOGICO = new HashSet<HISTORIAL_RECURSO_TECNOLOGICO>();
            this.MANTENIMIENTOes = new HashSet<MANTENIMIENTO>();
            this.RECURSO_TECNOLOGICO_X_CARACTERISTICA = new HashSet<RECURSO_TECNOLOGICO_X_CARACTERISTICA>();
            this.TURNOes = new HashSet<TURNO>();
            this.CENTRO_INVESTIGACION = new HashSet<CENTRO_INVESTIGACION>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public int id_modelo { get; set; }
        public int id_marca { get; set; }
        public byte[] imagen { get; set; }
        public int id_tipo_recurso_tecnologico { get; set; }
        public Nullable<int> id_responsable_tecnico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPONIBILIDAD> DISPONIBILIDADs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_RECURSO_TECNOLOGICO> HISTORIAL_RECURSO_TECNOLOGICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANTENIMIENTO> MANTENIMIENTOes { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSO_TECNOLOGICO_X_CARACTERISTICA> RECURSO_TECNOLOGICO_X_CARACTERISTICA { get; set; }
        public virtual RESPONSABLES_TECNICOS RESPONSABLES_TECNICOS { get; set; }
        public virtual TIPOS_RECURSOS_TECNOLOGICOS TIPOS_RECURSOS_TECNOLOGICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNO> TURNOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CENTRO_INVESTIGACION> CENTRO_INVESTIGACION { get; set; }
    }
}
