//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSO_TECNOLOGICO_X_CARACTERISTICA
    {
        public int id_recurso_tecnologico { get; set; }
        public int id_caracteristica { get; set; }
        public Nullable<int> valor { get; set; }
    
        public virtual CARACTERISTICA CARACTERISTICA { get; set; }
        public virtual RECURSOS_TECNOLOGICOS RECURSOS_TECNOLOGICOS { get; set; }
    }
}
