//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPONSABLES_TECNICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESPONSABLES_TECNICOS()
        {
            this.RECURSOS_TECNOLOGICOS = new HashSet<RECURSOS_TECNOLOGICOS>();
        }
    
        public int id_responsable_tecnico { get; set; }
        public int id_personal_cientifico { get; set; }
    
        public virtual PERSONAL_CIENTIFICO PERSONAL_CIENTIFICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSOS_TECNOLOGICOS> RECURSOS_TECNOLOGICOS { get; set; }
    }
}
