//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_Recursos_Tecnológicos.src.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO
    {
        public int id_turno { get; set; }
        public int id_recurso_tecnologico { get; set; }
        public Nullable<int> id_cientifico { get; set; }
        public int id_estado { get; set; }
        public Nullable<System.DateTime> fecha_hora_inicio { get; set; }
        public Nullable<System.DateTime> fecha_hora_fin { get; set; }
    
        public virtual CIENTIFICO CIENTIFICO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual RECURSOS_TECNOLOGICOS RECURSOS_TECNOLOGICOS { get; set; }
    }
}
